# Generated by Django 6.0.2 on 2026-04-30 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_remove_analyse_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analyse',
            name='resultat',
            field=models.CharField(max_length=100),
        ),
    ]
