# Generated by Django 6.0.2 on 2026-04-30 20:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_analyse_date_alter_analyse_resultat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyse',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Analyse', 'verbose_name_plural': 'Analyses'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.RemoveField(
            model_name='analyse',
            name='date',
        ),
        migrations.AddField(
            model_name='analyse',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyse',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='date_prescription',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de prescription'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='date_resultat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du résultat'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='medecin',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Médecin prescripteur'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observations / Notes'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='patient',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription"),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='patient',
            name='prenom',
            field=models.CharField(default='', max_length=100, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analyses.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='resultat',
            field=models.TextField(blank=True, null=True, verbose_name='Résultat'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='type_analyse',
            field=models.CharField(choices=[('sanguin', 'Analyse sanguine'), ('urine', 'Analyse urinaire'), ('bacterio', 'Bactériologie'), ('biochimie', 'Biochimie'), ('hormonale', 'Hormonale'), ('radiologie', 'Radiologie'), ('autre', 'Autre')], max_length=100, verbose_name="Type d'analyse"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='Âge'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
